### ISSUE TITLE
use within zsh causing TTY output to shift to bottom of screen

### ISSUE THREAD

**Issue by plukevdh** [garybernhardt/selecta#79] opened 2015-02-09 22:53 UTC
After watching Joe Armstrong's "The Mess We're In" talk from Strangeloop, I'm aware this is possibly caused by custom config specific to my machine, but I figured I'd post in hopes that it's an obvious fix to someone.

Using your demo script for project selection: `cd $(find ~/src -maxdepth 1 -type d | selecta)`, the output does the following in a zsh terminal:

![image](http://d.pr/i/19vXs/10CKCm7i+)

Is there a way to keep the output from jumping to the bottom of the terminal and, once a selection is made, to have the next line happen underneath the line selecta was called from?

**Comment by plukevdh** [comment] 2015-02-09 22:54
Also occurs in a bash shell.

**Comment by plukevdh** [comment] 2015-02-09 22:56
I am using iTerm, and Apple's built-in Terminal behaves the same.

**Comment by garybernhardt** [comment] 2015-02-10 00:56
That's Selecta's expected behavior, mostly because it's just easier to implement that way.

> Is there a way to keep the output from jumping to the bottom of the terminal

Yes, and it probably wouldn't be that difficult. However, your cursor is almost always at the bottom of a terminal, so this doesn't come up much.

> and, once a selection is made, to have the next line happen underneath the line selecta was called from?

Yes, we could make the prompt appear below the selected line (for example). However, there would still be about 20 blank lines *below* the prompt, where the UI used to be. At startup, we print 21 newlines to make room for the UI, and those can't be un-printed. The "alternate screen" behavior of the `?47h`/`?47l` escape codes *may* be able to avoid that, but I'm skeptical of how visually consistent terminals are with their support for those codes. I've been experimenting with them in another project, and Selecta may eventually be receive a backport of that terminal code if it works out.

My policy for Selecta is to keep terminal stuff simple (since we handle compatibility ourselves instead of relying on curses). I'm going to close this, but it will probably improve in the future.

**Closed by garybernhardt** 2015-02-10 00:56 UTC

**Comment by plukevdh** [comment] 2015-02-10 01:44
That's fair. Thanks for the informative feedback. Maybe I'm just a freak and tend to use `clear` more than most, which is why the behavior feels a bit more jarring.

**Comment by rschmitt** [comment] 2015-02-10 01:46
You can actually hit Ctrl-L instead of typing `clear`.
